/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `PublicodeAST`'s JSON-Schema definition
 * via the `patternProperty` ".*".
 */
export type RuleDefinition = CompilerMetadata & ChainedValue
export type CompilerMetadata = {
	id: Uid
	position: ASTNodePosition
} & PublicodesType
export type Uid = string
export type SourceFile = string
export type CursorIndex = number
export type LineNumber = number
export type ColumnNumber = number
/**
 * Inferred type of a Publicodes value
 */
export type PublicodesType =
	| {
			type: 'number'
			unit?: string
	  }
	| {
			type: 'texte' | 'boolean' | 'date'
	  }
export type ValueMechanism =
	| ExpressionMechanism
	| Value
	| IsApplicableMechanism
	| IsNotApplicableMechanism
	| SumMechanism
	| ProductMechanism
	| AllOfMechanism
	| MinOfMechanism
	| MaxOfMechanism
	| OneOfMechanism
	| NotDefined
	| VariationMechanism
export type ExpressionMechanism = {
	kind: 'expr'
	parameters: Expression
} & CompilerMetadata
export type Expression =
	| ConstantExpression
	| ReferenceExpression
	| BinaryOperationExpression
	| UnaryOperationExpression
export type ConstantExpression = {
	kind: 'constant'
} & (
	| {
			type: 'number'
			value: number
			unit?: string
	  }
	| {
			type: 'texte'
			value: string
	  }
	| {
			type: 'boolean'
			value: boolean
	  }
	| {
			type: 'date'
			/**
			 * Date in ISO 8601 format (YYYY-MM-DD)
			 */
			value: string
	  }
) &
	CompilerMetadata

export type ReferenceExpression = {
	kind: 'ref'
	parameters: string
} & CompilerMetadata
export type BinaryOperationExpression = {
	kind:
		| 'add'
		| 'sub'
		| 'mul'
		| 'div'
		| 'pow'
		| 'gt'
		| 'lt'
		| 'gteq'
		| 'lteq'
		| 'eq'
		| 'noteq'
		| 'and'
		| 'or'
		| 'max'
		| 'min'
	parameters: {
		left: Expression
		right: Expression
	}
} & CompilerMetadata
export type UnaryOperationExpression = {
	kind: 'neg'
	parameters: Expression
} & CompilerMetadata
export type Value = {
	kind: 'value'
	parameters: ChainedValue
} & CompilerMetadata
export type IsApplicableMechanism = {
	kind: 'is_applicable'
	parameters: ChainedValue
} & CompilerMetadata
export type IsNotApplicableMechanism = {
	kind: 'is_not_applicable'
	parameters: ChainedValue
} & CompilerMetadata
export type SumMechanism = {
	kind: 'sum'
	parameters: ChainedValue[]
} & CompilerMetadata
export type ProductMechanism = {
	kind: 'product'
	parameters: ChainedValue[]
} & CompilerMetadata
export type AllOfMechanism = {
	kind: 'all_of'
	parameters: ChainedValue[]
} & CompilerMetadata
export type MinOfMechanism = {
	kind: 'min_of'
	parameters: ChainedValue[]
} & CompilerMetadata
export type MaxOfMechanism = {
	kind: 'max_of'
	parameters: ChainedValue[]
} & CompilerMetadata
export type OneOfMechanism = {
	kind: 'one_of'
	parameters: ChainedValue[]
} & CompilerMetadata
export type NotDefined = {
	kind: 'not_defined'
} & CompilerMetadata
export type VariationMechanism = {
	kind: 'variations'
	parameters: {
		conditions: {
			if: ChainedValue
			then: ChainedValue
		}[]
		else?: ChainedValue
	}
} & CompilerMetadata
export type ChainedMechanism =
	| ContextMechanism
	| ApplicableIfMechanism
	| NotApplicableIfMechanism
	| TypeMechanism
	| DefaultMechanism
	| CeilingMechanism
	| FloorMechanism
	| RoundUpMechanism
	| RoundDownMechanism
	| RoundNearestMechanism
export type ContextMechanism = {
	kind: 'context'
	parameters: {
		[k: string]: ChainedValue
	}
} & CompilerMetadata
export type ApplicableIfMechanism = {
	kind: 'applicable_if'
	parameters: ChainedValue
} & CompilerMetadata
export type NotApplicableIfMechanism = {
	kind: 'not_applicable_if'
	parameters: ChainedValue
} & CompilerMetadata
export type TypeMechanism =
	| {
			parameters?: {
				type?: 'texte'
			}
	  }
	| {
			parameters?: {
				type?: 'boolean'
			}
	  }
	| {
			parameters?: {
				type?: 'date'
			}
	  }
	| {
			parameters?: {
				type?: 'number'
			}
	  }
export type DefaultMechanism = {
	kind: 'default'
	parameters: ChainedValue
} & CompilerMetadata
export type CeilingMechanism = {
	kind: 'ceiling'
	parameters: ChainedValue
} & CompilerMetadata
export type FloorMechanism = {
	kind: 'floor'
	parameters: ChainedValue
} & CompilerMetadata
export type RoundUpMechanism = {
	kind: 'round_up'
	parameters: ChainedValue
} & CompilerMetadata
export type RoundDownMechanism = {
	kind: 'round_down'
	parameters: ChainedValue
} & CompilerMetadata
export type RoundNearestMechanism = {
	kind: 'round_nearest'
	parameters: ChainedValue
} & CompilerMetadata

/**
 * JSON representation of the AST produced by the Publicodes compiler with the target `json_doc`.
 */
export interface PublicodeAST {
	[k: string]: RuleDefinition
}
export interface ASTNodePosition {
	file: SourceFile
	start: StartingPositionInTheSourceFile
	end: EndingPositionInTheSourceFile
}
export interface StartingPositionInTheSourceFile {
	index: CursorIndex
	line: LineNumber
	column: ColumnNumber
}
export interface EndingPositionInTheSourceFile {
	index: CursorIndex
	line: LineNumber
	column: ColumnNumber
}
export interface ChainedValue {
	value_mechanism: ValueMechanism
	chained_mechanisms: ChainedMechanism[]
}
