name: Install
inputs:
  node-version:
    default: 18.x
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
    - run: yarn install --refresh-lockfile --immutable
      shell: bash
