name: Install
inputs:
  node-version:
    description: 'Node.js version'
    default: 22.x
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
    - run: yarn install --refresh-lockfile --immutable
      shell: bash
