name: Check
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          node-version: 18
      - run: yarn build

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
        with:
          node-version: 18
      - run: yarn test

  typecheck:
    name: Typecheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: yarn test:type
