name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write # Required for OIDC

jobs:
  build-compiler:
    name: Ocaml compiler
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, macos, windows]
    steps:
      - uses: actions/checkout@v4
      - name: Build and test the ocaml compiler
        uses: ./.github/actions/build-compiler
        with:
          platform: ${{ matrix.platform }}

  release:
    needs: build-compiler
    name: Release
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.7.0
        with:
          publish: yarn release
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB }}
